name: Build, Deploy

on:
  push:
    branches: [ "master", "4.0-dev" ]
  pull_request:
    branches: [ "master", "4.0-dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean packageRelease
        
      - name : upload apk
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: 4.0-dev.apk
          path: ${{ github.workspace }}/app/build/outputs/apk/release
